spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: git@github.com:lazyratt/SpringCloudConfigTest.git
          search-paths: config
          username:
          password:


server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

feign:
  hystrix:
    enabled: true